config/routes.rb
Rails.application.routes.draw do
  root 'feeds#index'
  resources :feeds
  resources :awesomes
  get 'users/ranking' => 'users#ranking'
  get 'notifications/notify' => 'notifications#notify'

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/awesome.rb
class Awesome < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  belongs_to :user

  validates :body, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :awesomes
  has_many :awesome_feeds, through: :awesomes

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/awesomes_controller.rb
class AwesomesController < ApplicationController
  def create
    feed = Feed.find(awesome_params[:feed_id])
    current_user.awesomes.create(feed: feed)
    redirect_to feeds_path
  end

  def destroy
    awesome = Awesome.find(params[:id])
    awesome.destroy
    redirect_to feeds_path
  end

  private
  def awesome_params
    params.require(:awesome).permit(:feed_id)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feed = Feed.new
    @feeds = Feed.includes(:user).order('created_at DESC')
    ActiveRecord::Associations::Preloader.new.preload(current_user, :awesomes)
  end

  def create
    @feed = Feed.create(feed_params.merge(user: current_user))
    if @feed.valid?
      redirect_to feeds_path
    else
      @feeds = Feed.includes(:user).order('created_at DESC')
      render 'index'
    end
  end

  private
  def feed_params
    params.require(:feed).permit(:body, :image)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def notify
    ActionCable.server.broadcast 'web_notifications_channel', message: 'test'
    head :no_content
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def ranking
    @users = User.includes(:awesomes)
    @users = @users.sort_by {|u| u.awesomes.size }.reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_feed.html.slim
.panel.panel-feed
  .panel-heading
    .media
      .media-left
        a href='#'
          img.avatar src="/avatar.png"
      .media-body
        = feed.user.name || feed.user.email
        .feed_created_at.text-muted
          = feed.created_at.strftime("%Y/%m/%d %H:%M")
  .panel-body
    - if feed.image.present?
      = image_tag feed.image_url, style: 'width: 100%;'
    = feed.body
  .panel-footer
    - awesome = current_user.awesomes.find {|a| a.feed_id == feed.id }
    - if awesome.blank?
      = link_to 'Awesome', awesomes_path(awesome: {feed_id: feed.id}), method: :post, class: 'btn btn-danger'
    - else
      = link_to 'Unawesome', awesome, method: :delete, class: 'btn btn-info'

app/views/feeds/index.html.slim
.container
  = form_for @feed do |f|
    .panel.panel-feed
      - if @feed.errors.present?
        .panel-heading
          ul.form-error.list-unstyled.bg-danger
            - @feed.errors.full_messages.each do |msg|
              li= msg
      .panel-body
        .form-group#feed-data
          = f.text_area :body, placeholder: '今なにしてる？', class: 'form-control'
        .pull-right
          ul.list-inline
            li
              label for="feed_image" class='btn btn-default'
                | 写真
                = f.file_field :image, style: "display: none;"
                = f.hidden_field :image_cache
            li
              button.btn.btn-default 投稿する

  = render @feeds

app/views/layouts/application.html.slim
doctype html
html
  head
    title Awesome Leaders
    meta name='viewport' content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body
    .navbar.navbar-inverse.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        .navbar-brand = link_to 'Awesome Leaders', root_path
        - if signed_in?
          ul.nav.navbar-nav
            li = link_to 'Ranking', users_ranking_path
        .navbar-collapse.collapse.navbar-responsive-collapse
          - if signed_in?
            ul.nav.navbar-nav.navbar-right
              li.dropdown
                a.dropdown-toggle type='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='true'
                  = current_user.email
                  span.caret
                ul.dropdown-menu
                  li
                    a href='notifications/notify' Notify Hazard
                  li.divider
                  li
                    = link_to 'Logout', destroy_user_session_path, method: :delete

    = yield

    .hazard
      a.btn.btn-danger data-toggle='modal' data-target='#hazard-map'
        h2 危険です

    = link_to 'notifications/notify', id: 'hazard-button', remote: true do
      i.fa.fa-exclamation.fa-5x aria-hidden='true'

    #hazard-map.modal.fade
      .modal-dialog
        .modal-content
          .modal-header
            button.close type='button' data-dismiss='modal' aria-label='Close'
              span aria-hidden='true' &times;
            h3 浸水域マップ
          .modal-body
            img src='/hazard.jpg'
          .modal-footer
            button.btn.btn-default type='button' data-dismiss='modal'
              | OK

app/views/users/ranking.html.slim
.container
  ul.list-nonstyled
    - @users.each.with_index do |u, i|
      li = "#{i+1} #{u.email} #{u.awesomes.size} awesomes"